// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwd0DCHzmB44U0xK-XGVIS0Dm__UnW_sw',
    appId: '1:101861330698:web:4334fce0b8349e5d91f4f3',
    messagingSenderId: '101861330698',
    projectId: 'chalstock',
    authDomain: 'chalstock.firebaseapp.com',
    storageBucket: 'chalstock.firebasestorage.app',
    measurementId: 'G-PKBPPVST9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8drDCCySnuZb_viJmHWOIN4-zhk6zyZo',
    appId: '1:101861330698:android:097d5626609977e691f4f3',
    messagingSenderId: '101861330698',
    projectId: 'chalstock',
    storageBucket: 'chalstock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1C5EU-cJoCF5ynaxmS6IWm9K4pkJgfU',
    appId: '1:101861330698:ios:3e31f2616cf8d08691f4f3',
    messagingSenderId: '101861330698',
    projectId: 'chalstock',
    storageBucket: 'chalstock.firebasestorage.app',
    iosClientId:
        '101861330698-nj8vagp79frjq2m4ds20luldof3pqh4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockMvpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI1C5EU-cJoCF5ynaxmS6IWm9K4pkJgfU',
    appId: '1:101861330698:ios:3e31f2616cf8d08691f4f3',
    messagingSenderId: '101861330698',
    projectId: 'chalstock',
    storageBucket: 'chalstock.firebasestorage.app',
    iosClientId:
        '101861330698-nj8vagp79frjq2m4ds20luldof3pqh4j.apps.googleusercontent.com',
    iosBundleId: 'com.bluefog.stockMvpApp',
  );
}
